# Cấu hình mạng nội bộ container
port 6379
bind 0.0.0.0
protected-mode no

# Kích hoạt Cluster
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000

# Bảo mật (Khớp với mật khẩu 1234 của bạn)
requirepass 1234
masterauth 1234

# Quản lý tài nguyên (2048MB x 8 = 4GB)
maxmemory 2048mb
maxmemory-policy allkeys-lru

# Lưu trữ dữ liệu
appendonly yes
dir /data